# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcc < Formula
  desc "A CLI tool to manage and switch between multiple Kubernetes cluster configs."
  homepage "https://github.com/onggizam/mcc"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onggizam/mcc/releases/download/v0.0.2/mcc_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "5360dab1f07767701161fb59b7fedd2cb949c7cd8dd776eaac7dae3744788a75"

      def install
        bin.install "mcc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onggizam/mcc/releases/download/v0.0.2/mcc_0.0.2_Darwin_arm64.tar.gz"
      sha256 "0080b4de7d25f6a200839684d795f1dc9c51aa43030d7fd59b061c9f5ab5ba99"

      def install
        bin.install "mcc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onggizam/mcc/releases/download/v0.0.2/mcc_0.0.2_Linux_x86_64.tar.gz"
      sha256 "936f6922befaa0ecf7d431b3cbec525dc2e4b819ddfd23cf4f96ce5d5b8b0add"
      def install
        bin.install "mcc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onggizam/mcc/releases/download/v0.0.2/mcc_0.0.2_Linux_arm64.tar.gz"
      sha256 "48ecb35ba5bd1b9980a05ffe591bc5ddca6b65d16d4b5c9d6611555c6cb50d85"
      def install
        bin.install "mcc"
      end
    end
  end

  test do
    system "#{bin}/mcc version"
  end
end
